
export const dataProduct = [
{
				id: '0',
				info: 'Công thức không có ngũ cốc hoặc gluten, Earthborn Holistic Coastal Catch như một chế độ ăn kiêng không có protein cao, tiên tiến. Công thức đặc biệt này được đóng gói để cung cấp hương vị cho chú chó của bạn và tất cả các chất dinh dưỡng mà nó sẽ cần',
				pet: 'dog',
				slug: 'dog-0',
				price: 175000,
				brand: 'Pedigre',
				type: 'food',
				title: 'Sườn non',
				img: 'https://img.chewy.com/is/image/catalog/114316_MAIN._AC_SS190_V1489176455_.jpg',
				inCart: false,
				count: 1
			},
			{
				id: '1',
				pet: 'cat',
				slug: 'dog-1',
				type: 'toy',
				title: 'Thịt Khô',
				img: 'https://img.chewy.com/is/image/catalog/114326_MAIN._AC_SS190_V1539294265_.jpg',
				price: 600000,
				brand: 'Pedigre',
				info: 'Công thức không có ngũ cốc hoặc gluten, Earthborn Holistic Coastal Catch như một chế độ ăn kiêng không có protein cao, tiên tiến. Công thức đặc biệt này được đóng gói để cung cấp hương vị cho chú chó của bạn và tất cả các chất dinh dưỡng mà nó sẽ cần',
				inCart: false,
				count: 1
			},
			{
				id: '2',
				pet: 'dog',
				slug: 'dog-2',
				type: 'food',
				title: 'Ngũ cốc',
				img: 'https://img.chewy.com/is/image/catalog/100496_MAIN._AC_SS190_V1535579973_.jpg',
				price: 200000,
				brand: 'Nutrich',
				info: 'Công thức không có ngũ cốc hoặc gluten, Earthborn Holistic Coastal Catch như một chế độ ăn kiêng không có protein cao, tiên tiến. Công thức đặc biệt này được đóng gói để cung cấp hương vị cho chú chó của bạn và tất cả các chất dinh dưỡng mà nó sẽ cần',
				inCart: false,
				count: 1
			},
			{
				id: '3',
				pet: 'dog',
				slug: 'dog-3',
				type: 'food',
				title: 'Ngũ cốc dinh dưỡng',
				img: 'https://img.chewy.com/is/image/catalog/116635_MAIN._AC_SS190_V1537556921_.jpg',
				price: 250000,
				brand: 'Beneful',
				info: 'Công thức không có ngũ cốc hoặc gluten, Earthborn Holistic Coastal Catch như một chế độ ăn kiêng không có protein cao, tiên tiến. Công thức đặc biệt này được đóng gói để cung cấp hương vị cho chú chó của bạn và tất cả các chất dinh dưỡng mà nó sẽ cần',
				inCart: false,
				count: 1
			},
			{
				id: '4',
				pet: 'dog',
				slug: 'dog-4',
				type: 'food',
				title: 'Cơm Gà',
				img: 'https://img.chewy.com/is/image/catalog/67570_MAIN._AC_SS190_V1560367346_.jpg',
				price: 199000,
				brand: 'Beneful',
				info: 'Công thức không có ngũ cốc hoặc gluten, Earthborn Holistic Coastal Catch như một chế độ ăn kiêng không có protein cao, tiên tiến. Công thức đặc biệt này được đóng gói để cung cấp hương vị cho chú chó của bạn và tất cả các chất dinh dưỡng mà nó sẽ cần',
				inCart: false,
				count: 1
			},
			{
				id: '5',
				pet: 'dog',
				slug: 'dog-5',
				type: 'food',
				title: 'Món Chay',
				img: 'https://img.chewy.com/is/image/catalog/90938_MAIN._AC_SS190_V1574793476_.jpg',
				price: 150000,
				brand: "By Hill's Prescription Diet",
				info: 'Công thức không có ngũ cốc hoặc gluten, Earthborn Holistic Coastal Catch như một chế độ ăn kiêng không có protein cao, tiên tiến. Công thức đặc biệt này được đóng gói để cung cấp hương vị cho chú chó của bạn và tất cả các chất dinh dưỡng mà nó sẽ cần',
				inCart: false,
				count: 1
			},
			{
				id: '6',
				pet: 'dog',
				slug: 'dog-6',
				type: 'food',
				title: 'Thịt Bò',
				img: 'https://img.chewy.com/is/image/catalog/133886_MAIN._AC_SS190_V1579294685_.jpg',
				price: 300000,
				brand: 'American Journey',
				info: 'Công thức không có ngũ cốc hoặc gluten, Earthborn Holistic Coastal Catch như một chế độ ăn kiêng không có protein cao, tiên tiến. Công thức đặc biệt này được đóng gói để cung cấp hương vị cho chú chó của bạn và tất cả các chất dinh dưỡng mà nó sẽ cần',
				inCart: false,
				count: 1
			},
			{
				id: '7',
				pet: 'dog',
				slug: 'dog-7',
				type: 'toy',
				title: 'Vòng cổ thời trang',
				img: 'https://img.chewy.com/is/image/category/345-MAIN-dog-collars._AC_SX190_SY150_V1591323052_.jpg',
				price: 250000,
				brand: 'Collars',
				info: 'Công thức không có ngũ cốc hoặc gluten, Earthborn Holistic Coastal Catch như một chế độ ăn kiêng không có protein cao, tiên tiến. Công thức đặc biệt này được đóng gói để cung cấp hương vị cho chú chó của bạn và tất cả các chất dinh dưỡng mà nó sẽ cần',
				inCart: false,
				count: 1
			},
			{
				id: '8',
				pet: 'dog',
				slug: 'dog-8',
				type: 'toy',
				title: 'Khăn quàng cổ',
				img: 'https://img.chewy.com/is/image/catalog/177575_MAIN._AC_SS190_V1572446956_.jpg',
				price: 80000,
				brand: 'Pet First',
				info: 'Công thức không có ngũ cốc hoặc gluten, Earthborn Holistic Coastal Catch như một chế độ ăn kiêng không có protein cao, tiên tiến. Công thức đặc biệt này được đóng gói để cung cấp hương vị cho chú chó của bạn và tất cả các chất dinh dưỡng mà nó sẽ cần',
				inCart: false,
				count: 1
			},
			{
				id: '9',
				pet: 'dog',
				slug: 'dog-9',
				type: 'toy',
				title: 'Áo Phông',
				img: 'https://img.chewy.com/is/image/catalog/191919_Main._AC_SS190_V1582052958_.jpg',
				price: 70000,
				brand: 'Frisco',
				info: 'Công thức không có ngũ cốc hoặc gluten, Earthborn Holistic Coastal Catch như một chế độ ăn kiêng không có protein cao, tiên tiến. Công thức đặc biệt này được đóng gói để cung cấp hương vị cho chú chó của bạn và tất cả các chất dinh dưỡng mà nó sẽ cần',
				inCart: false,
				count: 1
			},
			{
				id: '10',
				pet: 'dog',
				slug: 'dog-10',
				type: 'toy',
				title: 'Áo phông Polo',
				img: 'https://img.chewy.com/is/image/catalog/139463_MAIN._AC_SS190_V1540401310_.jpg',
				price: 120000,
				brand: 'Mercedes',
				info: 'Công thức không có ngũ cốc hoặc gluten, Earthborn Holistic Coastal Catch như một chế độ ăn kiêng không có protein cao, tiên tiến. Công thức đặc biệt này được đóng gói để cung cấp hương vị cho chú chó của bạn và tất cả các chất dinh dưỡng mà nó sẽ cần',
				inCart: false,
				count: 1
			},
			{
				id: '11',
				pet: 'dog',
				slug: 'dog-11',
				type: 'toy',
				title: 'Giường cao cấp',
				img: 'https://img.chewy.com/is/image/catalog/144813_MAIN._AC_SS190_V1566936168_.jpg',
				price: 500000,
				brand: 'Frisco',
				info: 'Công thức không có ngũ cốc hoặc gluten, Earthborn Holistic Coastal Catch như một chế độ ăn kiêng không có protein cao, tiên tiến. Công thức đặc biệt này được đóng gói để cung cấp hương vị cho chú chó của bạn và tất cả các chất dinh dưỡng mà nó sẽ cần',
				inCart: false,
				count: 1
			},
			{
				id: '12',
				pet: 'dog',
				slug: 'dog-12',
				type: 'toy',
				title: 'Sofa ',
				img: 'https://img.chewy.com/is/image/catalog/127513_MAIN._AC_SS190_V1583506707_.jpg',
				price: 350000,
				brand: 'Frisco',
				info: 'Công thức không có ngũ cốc hoặc gluten, Earthborn Holistic Coastal Catch như một chế độ ăn kiêng không có protein cao, tiên tiến. Công thức đặc biệt này được đóng gói để cung cấp hương vị cho chú chó của bạn và tất cả các chất dinh dưỡng mà nó sẽ cần',
				inCart: false,
				count: 1
			},
			{
				id: '13',
				pet: 'dog',
				slug: 'dog-13',
				type: 'toy',
				title: 'Sofa ngủ',
				img: 'https://img.chewy.com/is/image/catalog/83896_MAIN._AC_SS190_V1566315794_.jpg',
				price: 450000,
				brand: 'Aspen Pet',
				info: 'Công thức không có ngũ cốc hoặc gluten, Earthborn Holistic Coastal Catch như một chế độ ăn kiêng không có protein cao, tiên tiến. Công thức đặc biệt này được đóng gói để cung cấp hương vị cho chú chó của bạn và tất cả các chất dinh dưỡng mà nó sẽ cần',
				inCart: false,
				count: 1
			},
			{
				id: '14',
				pet: 'cat',
				slug: 'cat-1',
				type: 'food',
				title: 'Gà Khô',
				img: 'https://img.chewy.com/is/catalog/69865._AC_SS190_V1460478783_.jpg',
				price: 250000,
				brand: 'Sheba',
				info: 'Công thức không có ngũ cốc hoặc gluten, Earthborn Holistic Coastal Catch như một chế độ ăn kiêng không có protein cao, tiên tiến. Công thức đặc biệt này được đóng gói để cung cấp hương vị cho chú chó của bạn và tất cả các chất dinh dưỡng mà nó sẽ cần',
				inCart: false,
				count: 1
			},
			{
				id: '15',
				pet: 'cat',
				slug: 'cat-2',
				type: 'food',
				title: 'Cá Hồi Dinh Dưỡng',
				img: 'https://img.chewy.com/is/image/catalog/124882_MAIN._AC_SS190_V1582317898_.jpg',
				price: 235000,
				brand: 'Sheba',
				info: 'Công thức không có ngũ cốc hoặc gluten, Earthborn Holistic Coastal Catch như một chế độ ăn kiêng không có protein cao, tiên tiến. Công thức đặc biệt này được đóng gói để cung cấp hương vị cho chú chó của bạn và tất cả các chất dinh dưỡng mà nó sẽ cần',
				inCart: false,
				count: 1
			},
			{
				id: '16',
				pet: 'cat',
				slug: 'cat-3',
				type: 'food',
				title: 'Cá Khô',
				img: 'https://img.chewy.com/is/image/catalog/49990_MAIN._AC_SS190_V1566489546_.jpg',
				price: 250000,
				brand: 'Kennels',
				info: 'Công thức không có ngũ cốc hoặc gluten, Earthborn Holistic Coastal Catch như một chế độ ăn kiêng không có protein cao, tiên tiến. Công thức đặc biệt này được đóng gói để cung cấp hương vị cho chú chó của bạn và tất cả các chất dinh dưỡng mà nó sẽ cần',
				inCart: false,
				count: 1
			},
			{
				id: '17',
				pet: 'cat',
				slug: 'cat-4',
				type: 'food',
				title: 'Pate Dinh Dưỡng',
				img: 'https://img.chewy.com/is/image/catalog/76350_MAIN._AC_SS190_V1565992024_.jpg',
				price: 189000,
				brand: 'Frisco',
				info: 'Công thức không có ngũ cốc hoặc gluten, Earthborn Holistic Coastal Catch như một chế độ ăn kiêng không có protein cao, tiên tiến. Công thức đặc biệt này được đóng gói để cung cấp hương vị cho chú chó của bạn và tất cả các chất dinh dưỡng mà nó sẽ cần',
				inCart: false,
				count: 1
			},
			{
				id: '18',
				pet: 'cat',
				slug: 'cat-5',
				type: 'toy',
				title: 'Lồng Di Chuyển',
				img: 'https://img.chewy.com/is/image/category/426-MAIN-cat-crates._AC_SX190_SY150_V1578684175_.jpg',
				price: 300000,
				brand: 'Kennels',
				info: 'Công thức không có ngũ cốc hoặc gluten, Earthborn Holistic Coastal Catch như một chế độ ăn kiêng không có protein cao, tiên tiến. Công thức đặc biệt này được đóng gói để cung cấp hương vị cho chú chó của bạn và tất cả các chất dinh dưỡng mà nó sẽ cần',
				inCart: false,
				count: 1
			},
			{
				id: '19',
				pet: 'cat',
				slug: 'cat-6',
				type: 'toy',
				title: 'Sofa',
				img: 'https://img.chewy.com/is/image/catalog/165315_Main._AC_SS190_V1576690674_.jpg',
				price: 450000,
				brand: 'Frisco',
				info: 'Công thức không có ngũ cốc hoặc gluten, Earthborn Holistic Coastal Catch như một chế độ ăn kiêng không có protein cao, tiên tiến. Công thức đặc biệt này được đóng gói để cung cấp hương vị cho chú chó của bạn và tất cả các chất dinh dưỡng mà nó sẽ cần',
				inCart: false,
				count: 1
			},
		
]

export const productDetail = [
			{
				id: '1',
				pet: 'dog',
				type: 'food',
				title: 'Sườn Chiên Sữa',
				img: 'public/img/dog-food1.jpg',
				price: 175000,
				brand: 'Mercedes',
				info: 'Công thức không có ngũ cốc hoặc gluten, Earthborn Holistic Coastal Catch như một chế độ ăn kiêng không có protein cao, tiên tiến. Công thức đặc biệt này được đóng gói để cung cấp hương vị cho chú chó của bạn và tất cả các chất dinh dưỡng mà nó sẽ cần',
				inCart: false,
				count: 1
			},
	]

export const Cart = []